import {createClient} from '@supabase/supabase-js';
import {Room,RoomEvent} from 'livekit-client';
import {socialStats} from '../public/social-stats.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s),uid=()=>session?.user.id,button=(label,action,data='',cls='')=>`<button type="button" class="${cls}" data-act="${action}" data-value="${esc(data)}">${label}</button>`;
const app=$('.app'),workspace=document.createElement('div');workspace.className='workspace';app.before(workspace);workspace.append(app);
const launch=document.createElement('div');launch.className='social-launch';launch.innerHTML='<button id="studyToggle" class="pill" aria-expanded="false" aria-controls="studyPanel">♧ Study Room <span id="socialCount"></span></button>';app.querySelector('header').after(launch);
const panel=document.createElement('aside');panel.id='studyPanel';panel.className='social-panel glass';panel.hidden=true;panel.setAttribute('aria-label','Study Room');panel.innerHTML='<div class="social-heading"><div><span class="tiny">FOCUS, TOGETHER</span><h2>Study Room</h2></div><button data-act="close" aria-label="Tutup Study Room">×</button></div><div id="socialNotice" role="status"></div><div id="socialTabs"></div><div id="socialBody"></div><div id="voiceDock"></div>';workspace.append(panel);
// Keep the official YouTube player in document flow, with its own reserved row.
const yt=$('#youtubeDock');if(yt){const slot=document.createElement('div');slot.className='youtube-slot';app.querySelector('main').append(slot);slot.append(yt);}
let client,config,session,home,roomId=null,snapshot,tab='rooms',roomTab='chat',channel,updates,voiceRoom,muted=true,deaf=false,replyTo=null,editId=null,pendingImage=null,focusStatus='online',lastActivity=Date.now(),draft='',refreshTimer,statsCache,voiceBusy=false,activeTimer=null,focusQueue=Promise.resolve(),typingAt=0;
const images=new Map(),previews=new Map(),speakers=new Set();let opening=false,showLobby=false;
function notice(message){$('#socialNotice').textContent=message||'';}
async function request(path,body){if(!session)throw Error('Masuk terlebih dahulu.');const r=await fetch('/api/social/'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+session.access_token,...(body!==undefined?{'Content-Type':'application/json'}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});const x=await r.json();if(!r.ok)throw Error(x.error||'Tidak dapat terhubung.');return x;}
const action=(op,p={})=>request('action',{op,p});
function safe(fn){return async(...args)=>{try{await fn(...args);}catch(e){notice(e.message);}};}
function openPanel(value=true){panel.hidden=!value;workspace.classList.toggle('social-open',value);$('#studyToggle').setAttribute('aria-expanded',String(value));if(value){document.body.classList.remove('zen');if(matchMedia('(max-width:900px)').matches)panel.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'start'});if(!opening){opening=true;safe(refresh)().finally(()=>opening=false);}}else $('#studyToggle').focus();}
$('#studyToggle').onclick=()=>openPanel(panel.hidden);
function input(name,label,type='text',extra=''){return `<label>${label}<input name="${name}" type="${type}" ${extra}></label>`;}
function render(){
 $('#socialTabs').innerHTML=session&&home?.profile?`<div class="social-tabs" role="tablist">${[['rooms','Room'],['friends','Teman'],['notifications','Kabar'],['progress','Progres'],['account','Akun']].map(([id,label])=>`<button data-act="tab" data-value="${id}" role="tab" aria-selected="${tab===id}">${label}${id==='notifications'&&home.notifications.some(n=>!n.read)?' •':''}</button>`).join('')}</div>`:'';
 const body=$('#socialBody');
 if(!config?.configured){body.innerHTML='<div class="social-empty"><span class="social-symbol">♧</span><h3>Ruang belajar bersama</h3><p>Study Room belum diaktifkan oleh pemilik website. Timer dan fitur pribadimu tetap siap digunakan.</p></div>';return;}
 if(!session){body.innerHTML=`<p class="social-muted">Belajar bareng, tetap punya ruang fokus.</p><form data-form="auth">${input('email','Email','email','required autocomplete="email"')}${input('password','Kata sandi','password','required minlength="8" autocomplete="current-password"')}<div class="social-actions"><button class="primary" name="mode" value="login">Masuk</button><button name="mode" value="signup">Daftar akun</button></div></form><p class="social-muted">Akun hanya diperlukan untuk fitur sosial.</p>`;return;}
 if(!home?.profile){body.innerHTML=`<h3>Pilih nama panggilan</h3><form data-form="profile">${input('username','Username','text','required pattern="[a-z0-9_]{3,24}" minlength="3" maxlength="24" autocomplete="username"')}<button class="primary">Simpan</button></form>`;return;}
 $('#socialCount').textContent=home.notifications.filter(n=>!n.read).length?'•':'';
 if(tab==='rooms')body.innerHTML=roomId&&snapshot&&!showLobby?renderRoom():renderLobby();
 if(tab==='friends')body.innerHTML=renderFriends();
 if(tab==='notifications')body.innerHTML=`<div class="social-row"><h3>Kabar terbaru</h3>${button('Tandai dibaca','read')}</div>${home.notifications.map(n=>`<div class="social-item ${n.read?'':'unread'}"><p>${esc(n.body)}</p><small>${date(n.created_at)}</small>${n.room_id?button('Buka room','notificationRoom',n.room_id):''}</div>`).join('')||'<p class="social-muted">Belum ada kabar baru.</p>'}`;
 if(tab==='account')body.innerHTML=renderAccount();
 if(tab==='progress')body.innerHTML=renderProgress();
 renderVoice();hydrateImages();hydrateLinks();
}
const date=s=>new Date(s).toLocaleString('id-ID',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
function renderLobby(){return `<div class="social-row"><h3>Temukan teman fokus</h3><span class="social-muted">${esc(home.profile.username)}</span></div><p class="social-muted">Gabung ruang yang tenang atau buat ruangmu sendiri.</p><form data-form="join" class="social-inline">${input('code','Kode undangan','text','required maxlength="10" placeholder="Kode room"')}<button class="primary">Gabung</button></form><details class="social-details"><summary>+ Buat study room</summary><form data-form="create">${input('name','Nama room','text','required maxlength="60" placeholder="Belajar malam"')}<div class="social-two"><label>Kapasitas<select name="capacity"><option>4</option><option>6</option><option selected>8</option></select></label><label>Undangan berlaku<select name="expiry"><option value="24">24 jam</option><option value="168">7 hari</option><option value="0">Tanpa batas</option></select></label></div><label class="social-check"><input type="checkbox" name="public"> Room publik</label><button class="primary">Buat room</button></form></details><div class="social-list">${home.rooms.map(r=>`<div class="social-item social-row"><div><strong>${esc(r.name)}</strong><small>${r.public?'Publik':'Privat'} · ${r.online} online · ${r.capacity} tempat${r.locked?' · Terkunci':''}</small></div>${button(r.joined?'Buka':'Gabung','join',r.id)}</div>`).join('')||'<p class="social-empty">Belum ada room. Mulai ruang pertamamu.</p>'}</div>`;}
function renderRoom(){const r=snapshot.room,me=snapshot.members.find(m=>m.user_id===uid()),admin=['host','moderator'].includes(me?.role);return `<div class="social-row">${button('‹ Daftar room','lobby')}<small>${r.public?'Publik':'Privat'} · ${snapshot.members.length}/${r.capacity}</small></div><h3 class="room-title">${esc(r.name)}</h3><div class="social-row room-summary"><span class="social-muted">${snapshot.members.filter(m=>Date.now()-Date.parse(m.seen_at)<90000).length} online</span>${button('Salin undangan','copyInvite')}</div><div class="social-tabs sub-tabs">${[['chat','Chat'],['members','Anggota'],['goals','Target'],['activity','Aktivitas']].map(([id,label])=>`<button data-act="roomTab" data-value="${id}" aria-pressed="${roomTab===id}">${label}</button>`).join('')}</div>${roomTab==='chat'?renderChat():roomTab==='members'?renderMembers():roomTab==='goals'?renderGoals():snapshot.activity.map(a=>`<div class="social-item"><p>${esc(a.body)}</p><small>${date(a.created_at)}</small></div>`).join('')}<details class="social-details"><summary>Opsi room</summary><p class="social-muted">Kode: <strong>${esc(r.code)}</strong>${r.expires_at?' · sampai '+date(r.expires_at):''}</p>${admin?`<form data-form="roomSettings"><label class="social-check"><input name="locked" type="checkbox" ${r.locked?'checked':''}> Kunci anggota baru</label><label class="social-check"><input name="chat" type="checkbox" ${r.chat_enabled?'checked':''}> Aktifkan chat</label><button>Simpan</button></form>`:''}${me?.role==='host'?button('Perbarui kode (24 jam)','rotate'):''}${button('Keluar dari room','leave','','danger')}</details>`;}
function linkify(text){return String(text).split(/(https?:\/\/[^\s<>]+)/g).map(part=>{if(!/^https?:\/\//.test(part))return esc(part);try{const u=new URL(part);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)return esc(part);return '<a href="'+esc(u.href)+'" target="_blank" rel="noopener noreferrer">'+esc(part)+'</a>';}catch{return esc(part);}}).join('');}
function renderChat(){const admin=['host','moderator'].includes(snapshot.members.find(m=>m.user_id===uid())?.role);return `<div class="chat-messages" id="chatMessages" role="log" aria-label="Pesan room">${snapshot.messages.map(m=>{const parent=snapshot.messages.find(x=>x.id===m.parent);const reactions=[...new Set(m.reactions.map(x=>x.emoji))];return `<article class="chat-message ${m.author===uid()?'own':''}"><div class="chat-author"><b>${esc(m.username)}</b><small>${new Date(m.created_at).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}${m.edited_at?' · diedit':''}</small></div>${parent?`<blockquote>${esc(parent.deleted?'Pesan dihapus':parent.username+': '+parent.body.slice(0,100))}</blockquote>`:''}<p>${m.deleted?'<i>Pesan dihapus</i>':linkify(m.body)}</p>${!m.deleted&&m.image_id?`<button class="chat-image-button" data-act="lightbox" data-value="${m.image_id}"><img data-chat-image="${m.image_id}" alt="Gambar dari ${esc(m.username)}" loading="lazy"></button>`:''}${!m.deleted&&/https?:\/\//.test(m.body)?`<div class="link-preview" data-preview="${esc(m.body.match(/https?:\/\/\S+/)?.[0]||'')}"></div>`:''}${!m.deleted?`<div class="chat-tools">${button('Balas','reply',m.id)}<details><summary aria-label="Aksi pesan">•••</summary><div>${['👍','❤️','🎉','🔥','👏'].map(e=>button(e,'react',m.id+'|'+e)).join('')}${m.author===uid()?button('Edit','edit',m.id):''}${m.author===uid()||admin?button('Hapus','deleteMessage',m.id):''}</div></details>${reactions.map(e=>button(esc(e)+' '+m.reactions.filter(x=>x.emoji===e).length,'react',m.id+'|'+e,m.reactions.some(x=>x.emoji===e&&x.user===uid())?'reacted':'')).join('')}</div>`:''}</article>`;}).join('')||'<p class="social-empty">Sapa teman belajarmu. Tetap tenang, tetap fokus.</p>'}</div><p id="typingStatus" class="social-muted typing-status" aria-live="polite"></p><form data-form="message"><div id="composeContext">${replyTo?'Membalas '+esc(snapshot.messages.find(m=>m.id===replyTo)?.username):editId?'Mengedit pesan':''}${replyTo||editId?button('Batal','cancelReply'):''}</div><textarea name="body" id="chatDraft" maxlength="2000" rows="2" placeholder="Pesan… gunakan @username" aria-label="Tulis pesan" ${snapshot.room.chat_enabled?'':'disabled'}>${esc(draft)}</textarea><div id="imagePreview">${pendingImage?'<span>Gambar siap dikirim</span>'+button('Hapus','clearImage'):''}</div><progress id="uploadProgress" max="100" value="0" hidden></progress><div class="social-row"><label class="attach-image" title="Lampirkan gambar">▧ Gambar<input type="file" id="chatImage" accept="image/jpeg,image/png,image/webp" hidden ${snapshot.room.chat_enabled?'':'disabled'}></label><div>${button('☺','emoji')}<button class="primary" ${snapshot.room.chat_enabled?'':'disabled'}>Kirim</button></div></div></form>`;}
function renderMembers(){const me=snapshot.members.find(m=>m.user_id===uid());return snapshot.members.map(m=>`<div class="social-item"><div class="social-row"><div class="member-name"><span class="avatar ${speakers.has(m.user_id)?'speaking':''}" data-speaker="${m.user_id}">${esc(m.username[0].toUpperCase())}</span><div><strong>${esc(m.username)}${m.user_id===uid()?' (kamu)':''}</strong><small>${esc(m.role)}${voiceRoom&&(m.user_id===uid()||voiceRoom.remoteParticipants.has(m.user_id))?" · In voice":""} · ${Date.now()-Date.parse(m.seen_at)>90000?'Offline':({focusing:'Fokus',break:'Istirahat',away:'Away',offline:'Offline',online:'Online'}[m.status])}</small></div></div>${m.voice_muted?'<span title="Mic dibatasi host">🔇</span>':''}</div>${m.user_id!==uid()?`<details class="member-actions"><summary>Opsi anggota</summary><div class="social-actions">${button('Tambah teman','friend_request',m.user_id)}${button('Blokir','block',m.user_id)}${button('Laporkan','report',m.user_id)}${me?.role==='host'||me?.role==='moderator'&&m.role==='member'?`${m.role!=='host'?button(m.voice_muted?'Izinkan mic':'Mute mic',m.voice_muted?'voice_allow':'voice_mute',m.user_id)+button('Keluarkan','kick',m.user_id)+button('Ban','ban',m.user_id):''}${me.role==='host'&&m.role!=='host'?button(m.role==='moderator'?'Jadikan anggota':'Jadikan moderator','moderator',m.user_id):''}`:''}</div><label>Volume suara<input type="range" min="0" max="100" value="100" data-volume-user="${m.user_id}"></label></details>`:''}</div>`).join('');}
function renderGoals(){return `<p class="social-muted">Menit dan sesi dihitung otomatis dari fokus yang selesai.</p>${snapshot.goals.map(g=>{const total=g.progress.reduce((n,p)=>n+p.value,0);return `<div class="social-item"><strong>${esc(g.title)}</strong><p>${total} / ${g.target} ${g.kind==='minutes'?'menit':g.kind==='sessions'?'sesi':'task'}</p><progress max="${g.target}" value="${Math.min(g.target,total)}"></progress><small>${g.progress.map(p=>esc(p.username)+': '+p.value).join(' · ')||'Belum ada kontribusi'}</small>${g.kind==='task'?button(g.progress.some(p=>p.user_id===uid())?'Selesai ✓':'Tandai task selesai','goal_done',g.id):''}</div>`;}).join('')}<details class="social-details"><summary>+ Target bersama</summary><form data-form="goal">${input('title','Nama target','text','required maxlength="100"')}<div class="social-two"><label>Jenis<select name="kind"><option value="minutes">Menit fokus</option><option value="sessions">Sesi fokus</option><option value="task">Task per anggota</option></select></label>${input('target','Target','number','required min="1" max="10080" value="4"')}</div><button class="primary">Tambah target</button></form></details>`;}
function renderFriends(){return `<form data-form="search" class="social-inline">${input('query','Cari username','text','required minlength="3" maxlength="24"')}<button>Cari</button></form><div id="friendSearch"></div>${home.friends.map(f=>`<div class="social-item"><strong>${esc(f.username)}</strong><small>${f.accepted?(f.online?(f.status==='focusing'?'Sedang fokus':'Online'):'Offline'):f.sender===uid()?'Permintaan terkirim':'Ingin menjadi temanmu'}</small><div class="social-actions">${!f.accepted&&f.recipient===uid()?button('Terima','friend_accept',f.id)+button('Tolak','friend_reject',f.id):''}${f.accepted&&roomId?button('Undang ke room','invite',f.id):''}${button(f.accepted?'Hapus teman':'Batalkan','friend_remove',f.id)}</div></div>`).join('')||'<p class="social-empty">Teman belajarmu akan muncul di sini.</p>'}`;}
function renderAccount(){const p=home.profile.preferences||{};return `<h3>@${esc(home.profile.username)}</h3><form data-form="preferences"><label class="social-check"><input name="share" type="checkbox" ${home.profile.share_status?'checked':''}> Bagikan status kepada teman</label><h4>Notifikasi</h4>${[['friend','Permintaan teman'],['invite','Undangan room'],['mention','Mention'],['reply','Balasan'],['focus','Fokus selesai'],['achievement','Achievement'],['streak','Streak']].map(([id,label])=>`<label class="social-check"><input name="${id}" type="checkbox" ${p[id]!==false?'checked':''}> ${label}</label>`).join('')}<p class="social-muted">Pengingat istirahat dan suara ada di Pengaturan utama. Saat fokus, kabar sosial tetap tersimpan tanpa pop-up.</p><button class="primary">Simpan preferensi</button></form><details class="social-details"><summary>Pengaturan voice saat fokus</summary><p class="social-muted">Mic tidak berubah otomatis. Gunakan tombol Mic dan Deafen kapan pun diperlukan.</p></details>${button('Keluar akun','signout','','danger')}`;}
function renderProgress(){if(!statsCache)return '<p class="social-muted">Memuat progres…</p>';const day=new Intl.DateTimeFormat('en-CA',{timeZone:home.profile.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),s=socialStats(statsCache.sessions,day);return `<div class="social-row"><h3>Level ${s.level}</h3><span>${s.xp} XP</span></div><progress max="500" value="${s.xp%500}"></progress><div class="social-stat-grid">${[['Hari ini',s.today+' mnt'],['7 hari',s.week+' mnt'],['Total',s.total+' mnt'],['Sesi',s.count],['Rata-rata',Math.round(s.average)+' mnt'],['Streak',s.streak+' hari'],['Terpanjang',s.longest+' hari']].map(([l,v])=>`<div><small>${l}</small><strong>${v}</strong></div>`).join('')}</div><p class="social-muted">XP dari menit fokus, sesi selesai, dan bonus target harian 120 menit. Pesan tidak menghasilkan XP.</p><h4>Pencapaian</h4><div class="social-badges">${s.badges.map(([b,yes])=>`<span class="${yes?'earned':''}">${yes?'✓':'○'} ${b}</span>`).join('')}</div><h4>Leaderboard</h4><form data-form="leaderboard" class="social-two"><label>Lingkup<select name="scope"><option value="friends">Teman</option>${roomId?'<option value="room">Room ini</option>':''}</select></label><label>Periode<select name="period"><option value="week">Minggu ini</option><option value="month">Bulan ini</option></select></label><button>Tampilkan</button></form><div id="leaderboard"></div><small>Progres akun hanya mencatat sesi yang dimulai saat masuk. Statistik pribadimu tetap ada di tab Statistik.</small>`;}
async function refresh(){if(!client||!session){render();return;}home=await action('home');if(roomId){try{snapshot=await action('room',{room:roomId});if(snapshot.needsProfile)throw Error('Lengkapi profil dahulu.');}catch(e){await disconnectVoice();roomId=null;snapshot=null;notice(e.message);}}if(tab==='progress')statsCache=await action('stats');const focused=document.activeElement;if(focused?.closest('#socialBody form')&&['INPUT','TEXTAREA','SELECT'].includes(focused.tagName)&&focused.id!=='chatDraft')return;const id=focused?.id,selection=focused?.selectionStart;draft=$('#chatDraft')?.value??draft;const list=$('#chatMessages'),scroll=list?.scrollTop,atBottom=!list||list.scrollHeight-list.clientHeight-list.scrollTop<80;render();if(id&&$('#'+id)){const el=$('#'+id);el.focus({preventScroll:true});if(selection!=null&&el.setSelectionRange)el.setSelectionRange(selection,selection);}const newList=$('#chatMessages');if(newList)newList.scrollTop=atBottom?newList.scrollHeight:scroll;}
function scheduleRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>safe(refresh)(),350);}
async function join(p){const r=await action('join',p);if(roomId!==r.room&&voiceRoom)await disconnectVoice();roomId=r.room;showLobby=false;tab='rooms';roomTab='chat';draft='';replyTo=null;editId=null;pendingImage=null;await subscribeRoom();await refresh();await heartbeat();}
async function subscribeRoom(){if(channel)await client.removeChannel(channel);if(!roomId)return;channel=client.channel('af:'+roomId,{config:{private:true,presence:{key:uid()}}});channel.on('broadcast',{event:'typing'},({payload})=>{const member=snapshot?.members.find(m=>m.user_id===payload.id);if(member&&member.user_id!==uid()&&$('#typingStatus')){$('#typingStatus').textContent=member.username+' sedang mengetik…';setTimeout(()=>{if($('#typingStatus'))$('#typingStatus').textContent='';},3000);}}).on('presence',{event:'sync'},()=>{const state=channel.presenceState();for(const m of snapshot?.members||[]){const current=state[m.user_id]?.[0];if(current){m.status=current.status||'online';m.seen_at=new Date().toISOString();}}if(tab==='rooms'&&roomTab==='members')render();}).subscribe(status=>{if(status==='SUBSCRIBED')channel.track({id:uid(),status:focusStatus});});}
async function heartbeat(){if(!roomId||!session||!home?.profile)return;const status=Date.now()-lastActivity>120000&&focusStatus==='online'?'away':focusStatus;await action('presence',{room:roomId,status});await channel?.track({id:uid(),status,inVoice:!!voiceRoom});}
['pointerdown','keydown'].forEach(e=>document.addEventListener(e,()=>lastActivity=Date.now(),{passive:true}));
setInterval(()=>{if(session){safe(heartbeat)();if(!panel.hidden)safe(refresh)();else if(voiceRoom)safe(async()=>{try{await action('voice_access',{room:roomId});}catch(e){await disconnectVoice();roomId=null;snapshot=null;render();throw e;}})();}},30000);
async function hydrateImages(){for(const img of panel.querySelectorAll('[data-chat-image]')){const id=img.dataset.chatImage;try{let item=images.get(id);if(!item||item.until<Date.now()){item={...(await request(`image?room=${roomId}&image=${id}`)),until:Date.now()+240000};images.set(id,item);}if(img.isConnected)img.src=item.url;}catch{img.alt='Gambar tidak tersedia';}}}
async function hydrateLinks(){for(const el of panel.querySelectorAll('[data-preview]')){const url=el.dataset.preview;if(!previews.has(url))try{previews.set(url,await request('preview',{url,room:roomId}));}catch{previews.set(url,{});}const p=previews.get(url);if(el.isConnected&&p.title){el.textContent=p.title+(p.description?' — '+p.description:'');}}}
async function compress(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024)throw Error('Pilih JPG, PNG, atau WebP maksimal 15 MB.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.82));if(!blob||blob.size>2097152)throw Error('Gambar terlalu besar setelah dikompres. Pilih gambar lebih kecil.');return blob;}
async function upload(file){const blob=await compress(file);const progress=$('#uploadProgress');progress.hidden=false;const x=await new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST','/api/social/image?room='+roomId);xhr.setRequestHeader('Authorization','Bearer '+session.access_token);xhr.setRequestHeader('Content-Type',blob.type);xhr.upload.onprogress=e=>{if(e.lengthComputable)progress.value=e.loaded/e.total*100;};xhr.onerror=()=>reject(Error('Upload gagal.'));xhr.onload=()=>{try{const r=JSON.parse(xhr.responseText);xhr.status<300?resolve(r):reject(Error(r.error));}catch{reject(Error('Upload gagal.'));}};xhr.send(blob);});pendingImage=x.id;progress.hidden=true;const area=$('#imagePreview');area.innerHTML='<img alt="Pratinjau gambar yang akan dikirim">'+button('Hapus','clearImage');const local=URL.createObjectURL(blob);area.querySelector('img').src=local;area.querySelector('img').onload=()=>URL.revokeObjectURL(local);}
function renderVoice(){const dock=$('#voiceDock');if(!roomId){dock.innerHTML='';return;}dock.innerHTML=`<div class="voice-title"><span>◉ Voice room</span><small>${voiceRoom?'Terhubung · '+(voiceRoom.remoteParticipants.size+1)+' peserta':'Belajar sambil terhubung'}</small></div>${voiceRoom?`<div class="social-actions">${button(muted?'Mic mati':'Mic aktif','mic','',''+(muted?'':'active'))}${button(deaf?'Dengar mati':'Deafen','deafen')}${button('Putus','voiceLeave')}</div><details class="social-details"><summary>Perangkat audio</summary><label>Mikrofon<select id="voiceInput"></select></label><label>Output<select id="voiceOutput"></select></label><small>Pilihan output mengikuti dukungan browser.</small></details>`:button(voiceBusy?'Menghubungkan…':'Gabung voice','voiceJoin','','primary full')}<p class="social-muted">${config?.voice?'Mikrofon dimulai dalam keadaan mati.':'Voice belum diaktifkan oleh pemilik website.'}</p>`;if(voiceRoom)safe(devices)();}
async function devices(){const devices=await navigator.mediaDevices.enumerateDevices();for(const [id,kind]of[['voiceInput','audioinput'],['voiceOutput','audiooutput']]){const el=$('#'+id);if(!el)continue;el.innerHTML=devices.filter(d=>d.kind===kind).map((d,i)=>`<option value="${esc(d.deviceId)}">${esc(d.label||'Perangkat '+(i+1))}</option>`).join('')||'<option value="default">Default sistem</option>';el.value=voiceRoom?.getActiveDevice(kind)||el.options[0]?.value;}}
async function connectVoice(){if(voiceBusy||voiceRoom)return;voiceBusy=true;renderVoice();try{const access=await request('voice',{room:roomId});const v=new Room({adaptiveStream:true,dynacast:true});voiceRoom=v;
 v.on(RoomEvent.TrackSubscribed,(track,publication,participant)=>{if(track.kind==='audio'){const audio=track.attach();audio.dataset.voiceAudio=participant.identity;audio.muted=deaf;document.body.append(audio);}}).on(RoomEvent.TrackUnsubscribed,track=>track.detach().forEach(el=>el.remove())).on(RoomEvent.ActiveSpeakersChanged,people=>{speakers.clear();people.forEach(p=>speakers.add(p.identity));panel.querySelectorAll('[data-speaker]').forEach(el=>el.classList.toggle('speaking',speakers.has(el.dataset.speaker)));}).on(RoomEvent.ParticipantConnected,renderVoice).on(RoomEvent.ParticipantDisconnected,renderVoice).on(RoomEvent.LocalTrackUnpublished,()=>{muted=true;renderVoice();}).on(RoomEvent.Disconnected,()=>{voiceRoom=null;document.querySelectorAll('[data-voice-audio]').forEach(el=>el.remove());renderVoice();});
 await v.connect(access.url,access.token);await v.startAudio();muted=true;await action('voice_join',{room:roomId});await heartbeat();renderVoice();}catch(e){await disconnectVoice();throw e;}finally{voiceBusy=false;renderVoice();}}
async function disconnectVoice(){const v=voiceRoom;voiceRoom=null;if(v)await v.disconnect();document.querySelectorAll('[data-voice-audio]').forEach(el=>el.remove());muted=true;deaf=false;renderVoice();}
panel.addEventListener('input',e=>{if(e.target.id==='chatDraft'){draft=e.target.value;if(channel&&Date.now()-typingAt>1500){typingAt=Date.now();channel.send({type:'broadcast',event:'typing',payload:{id:uid()}});}}if(e.target.dataset.volumeUser)voiceRoom?.remoteParticipants.get(e.target.dataset.volumeUser)?.setVolume(Number(e.target.value)/100);});
panel.addEventListener('change',safe(async e=>{if(e.target.id==='chatImage'&&e.target.files[0])await upload(e.target.files[0]);if(e.target.id==='voiceInput')await voiceRoom?.switchActiveDevice('audioinput',e.target.value);if(e.target.id==='voiceOutput')await voiceRoom?.switchActiveDevice('audiooutput',e.target.value);}));
panel.addEventListener('click',safe(async e=>{const b=e.target.closest('[data-act]');if(!b)return;const a=b.dataset.act,v=b.dataset.value;notice('');
 if(a==='close'){openPanel(false);return;}
 if(a==='tab'){draft=$('#chatDraft')?.value??draft;tab=v;await refresh();return;}
 if(a==='join'){await join({room:v});return;}
 if(a==='lobby'){showLobby=true;render();return;}
 if(a==='roomTab'){draft=$('#chatDraft')?.value??draft;roomTab=v;render();return;}
 if(a==='copyInvite'){const u=new URL(location.href);u.search='';u.searchParams.set('room',snapshot.room.code);await navigator.clipboard.writeText(u.href);notice('Tautan undangan disalin.');return;}
 if(a==='notificationRoom'){const n=home.notifications.find(n=>n.room_id===v&&n.kind==='invite'),code=n?.body.match(/Kode: ([A-F0-9]+)/)?.[1];await join(code?{code}:{room:v});return;}
 if(a==='signout'){await disconnectVoice();if(channel)await client.removeChannel(channel);await client.auth.signOut();roomId=null;home=null;session=null;render();return;}
 if(a==='voiceJoin'){await connectVoice();return;}
 if(a==='voiceLeave'){await disconnectVoice();return;}
 if(a==='mic'){if(!voiceRoom)return;const access=await action('voice_access',{room:roomId});if(access.voice_muted&&!muted){}else if(access.voice_muted)throw Error('Mic sedang dibatasi host.');await voiceRoom.localParticipant.setMicrophoneEnabled(muted);muted=!muted;renderVoice();return;}
 if(a==='deafen'){deaf=!deaf;document.querySelectorAll('[data-voice-audio]').forEach(el=>el.muted=deaf);renderVoice();return;}
 if(a==='reply'||a==='edit'){replyTo=a==='reply'?v:null;editId=a==='edit'?v:null;if(editId)draft=snapshot.messages.find(m=>m.id===v).body;render();$('#chatDraft')?.focus();return;}
 if(a==='cancelReply'){replyTo=null;editId=null;draft='';render();return;}
 if(a==='clearImage'){pendingImage=null;$('#imagePreview').innerHTML='';return;}
 if(a==='emoji'){const el=$('#chatDraft');el.value+=' 😊';draft=el.value;el.focus();return;}
 if(a==='lightbox'){const image=images.get(v);if(!image)return;const dialog=document.createElement('dialog');dialog.className='image-lightbox';dialog.innerHTML='<button aria-label="Tutup gambar">×</button><img alt="Gambar dari chat">';dialog.querySelector('img').src=image.url;document.body.append(dialog);dialog.querySelector('button').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.showModal();return;}
 if(a==='read')await action('notifications_read');
 else if(a==='react'){const [message,emoji]=v.split('|');await action('reaction',{room:roomId,message,emoji});}
 else if(a==='deleteMessage'){if(!confirm('Hapus pesan ini?'))return;await action('message_delete',{room:roomId,message:v});}
 else if(a==='leave'){if(!confirm('Keluar dari room ini?'))return;await action('leave',{room:roomId});await disconnectVoice();roomId=null;snapshot=null;if(channel)await client.removeChannel(channel);}
 else if(a==='rotate')await action('room_settings',{room:roomId,expiry:24});
 else if(a==='goal_done')await action(a,{room:roomId,goal:v});
 else {const p={room:roomId,user:v};if(['kick','ban','block','friend_remove'].includes(a)&&!confirm('Lanjutkan tindakan ini?'))return;if(a==='report'){p.reason=prompt('Alasan laporan (minimal 5 karakter):');if(!p.reason)return;}if(a==='moderator')p.enabled=snapshot.members.find(m=>m.user_id===v)?.role!=='moderator';const result=await action(a,p);if(result.warning)notice(result.warning);else notice('Tersimpan.');}
 await refresh();
}));
panel.addEventListener('submit',safe(async e=>{const form=e.target.closest('[data-form]');if(!form)return;e.preventDefault();document.activeElement?.blur();notice('');const f=new FormData(form),p=Object.fromEntries(f),kind=form.dataset.form;const submit=e.submitter;submit?.setAttribute('disabled','');try{
 if(kind==='auth'){const signup=submit?.value==='signup';const result=signup?await client.auth.signUp({email:p.email,password:p.password,options:{emailRedirectTo:location.origin}}):await client.auth.signInWithPassword({email:p.email,password:p.password});if(result.error)throw result.error;if(signup&&!result.data.session)notice('Periksa email untuk konfirmasi akun, lalu masuk.');return;}
 if(kind==='profile'){await action('profile',{username:p.username,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});await refresh();return;}
 if(kind==='create'){const r=await action('create',{...p,public:f.has('public'),capacity:Number(p.capacity),expiry:Number(p.expiry)});await join({room:r.room});return;}
 if(kind==='join'){await join({code:p.code.trim().toUpperCase()});return;}
 if(kind==='message'){if(!p.body.trim()&&!pendingImage)return;await action(editId?'message_edit':'message_send',{room:roomId,body:p.body,...(editId?{message:editId}:{}),...(replyTo?{parent:replyTo}:{}),...(pendingImage?{image:pendingImage}:{})});draft='';$('#chatDraft').value='';replyTo=null;editId=null;pendingImage=null;}
 if(kind==='goal')await action('goal_create',{...p,target:Number(p.target),room:roomId});
 if(kind==='roomSettings')await action('room_settings',{room:roomId,locked:f.has('locked'),chat:f.has('chat')});
 if(kind==='search'){const people=await action('search',p);$('#friendSearch').innerHTML=people.map(u=>`<div class="social-row social-item"><span>${esc(u.username)}</span>${button('Tambah','friend_request',u.id)}</div>`).join('')||'<p>Username tidak ditemukan.</p>';return;}
 if(kind==='preferences'){const preferences={};for(const key of ['friend','invite','mention','reply','focus','achievement','streak'])preferences[key]=f.has(key);await action('preferences',{share:f.has('share'),preferences});notice('Preferensi disimpan.');}
 if(kind==='leaderboard'){const rows=await action('leaderboard',{...p,room:roomId});$('#leaderboard').innerHTML=rows.map((r,i)=>`<div class="social-row social-item"><span>${i+1}. ${esc(r.username)}</span><b>${r.minutes} mnt</b></div>`).join('')||'<p class="social-muted">Belum ada sesi selesai pada periode ini.</p>';return;}
 await refresh();}finally{submit?.removeAttribute('disabled');}
}));
// Ordered bridge: reward only sessions measured by the authenticated server clock.
window.addEventListener('lofi:timer',e=>{const d=e.detail;focusStatus=d.timer.running?d.timer.mode==='focus'?'focusing':'break':'online';if(!session||!home?.profile)return;focusQueue=focusQueue.then(async()=>{if(d.event==='finish'&&d.previous?.mode==='focus'){await action('focus',{id:d.previous.id,state:d.skipped?'cancel':'finish'});activeTimer=null;}if(activeTimer&&activeTimer!==d.timer.id){await action('focus',{id:activeTimer,state:'cancel'});activeTimer=null;}if(d.timer.mode==='focus'){if(d.timer.running){await action('focus',{id:d.timer.id,state:activeTimer===d.timer.id?'resume':'start',duration:d.timer.total,room:roomId});activeTimer=d.timer.id;}else if(activeTimer===d.timer.id)await action('focus',{id:activeTimer,state:'pause'});}await heartbeat();}).catch(e=>notice('Sinkronisasi fokus: '+e.message));});
async function boot(){try{config=await fetch('/api/social/config').then(r=>r.json());if(!config.configured){render();return;}client=createClient(config.url,config.key);client.auth.onAuthStateChange((event,s)=>{session=s;setTimeout(()=>safe(async()=>{if(!s){if(updates)await client.removeChannel(updates);if(channel)await client.removeChannel(channel);home=null;roomId=null;snapshot=null;await disconnectVoice();render();return;}await client.realtime.setAuth(s.access_token);if(updates)await client.removeChannel(updates);updates=client.channel('af-updates-'+s.user.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'af_updates',filter:'recipient=eq.'+s.user.id},scheduleRefresh).subscribe();await refresh();if(event==='SIGNED_IN'||event==='INITIAL_SESSION'){const state=await action('stats');activeTimer=state.active?.id||null;window.dispatchEvent(new Event('lofi:sync'));}const code=new URL(location.href).searchParams.get('room');if(code&&home.profile){openPanel();await join({code});history.replaceState(null,'',location.pathname);}else if(home.profile?.last_room&&!roomId)await join({room:home.profile.last_room});})(),0);});const result=await client.auth.getSession();session=result.data.session;render();}catch{notice('Study Room tidak dapat terhubung. Coba muat ulang.');render();}}
boot();


