import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import worker from '../src/worker.mjs';import {defaults} from '../public/core.mjs';
const db=new DatabaseSync(':memory:');db.exec(fs.readFileSync('drizzle/0000_profiles.sql','utf8'));
const DB={prepare(sql){return {bind(...args){return {async first(){return db.prepare(sql).get(...args);},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};}};}};}};
const bucket=new Map();const UPLOADS={async put(k,b,m){bucket.set(k,{body:b,size:b.byteLength,...m})},async head(k){return bucket.get(k)},async get(k,o){const v=bucket.get(k);return o?.range?{...v,body:v.body.slice(o.range.offset,o.range.offset+o.range.length)}:v},async delete(k){bucket.delete(k)}};
const env={DB,UPLOADS,ASSETS:{fetch:()=>new Response('asset')}};const origin='https://test.example';
const req=(p,method='GET',body,cookie,headers={})=>new Request(origin+p,{method,headers:{Origin:origin,...(cookie?{Cookie:cookie}:{}),...headers},...(['GET','HEAD'].includes(method)?{}:{body:typeof body==='string'||body instanceof ArrayBuffer?body:JSON.stringify(body)})});
test('Profiles persist, reject stale revisions, and isolate visitors',async()=>{const init=await worker.fetch(req('/api/state'),env);const cookie=init.headers.get('Set-Cookie').split(';')[0];assert.match(init.headers.get('Set-Cookie'),/HttpOnly/);assert.match(init.headers.get('Set-Cookie'),/Secure/);let d=defaults();d.tasks=[{id:'a',title:'Task',est:1}];const saved=await worker.fetch(req('/api/state','PUT',{data:d,revision:0},cookie),env);assert.equal(saved.status,200);assert.equal((await saved.json()).revision,1);const read=await worker.fetch(req('/api/state','GET',null,cookie),env);assert.equal((await read.json()).data.tasks[0].title,'Task');const stale=await worker.fetch(req('/api/state','PUT',{data:d,revision:0},cookie),env);assert.equal(stale.status,409);const other=await worker.fetch(req('/api/state'),env);assert.equal((await other.json()).data,null);});
test('Cross origin writes and invalid settings are rejected',async()=>{const cross=await worker.fetch(req('/api/state','PUT',{},null,{Origin:'https://bad.example'}),env);assert.equal(cross.status,403);const init=await worker.fetch(req('/api/state'),env);const cookie=init.headers.get('Set-Cookie').split(';')[0];const d=defaults();d.settings.focusMinutes=-1;assert.equal((await worker.fetch(req('/api/state','PUT',{data:d,revision:0},cookie),env)).status,400);});
test('Image upload, range access, wrong type and ownership boundaries',async()=>{const init=await worker.fetch(req('/api/state'),env);const cookie=init.headers.get('Set-Cookie').split(';')[0];const file=fs.readFileSync('public/assets/scene-1.png');let r=await worker.fetch(req('/api/upload','POST',file.buffer.slice(file.byteOffset,file.byteOffset+file.byteLength),cookie,{'Content-Type':'image/png'}),env);assert.equal(r.status,200);const media=await r.json();r=await worker.fetch(req(media.url,'GET',null,cookie,{'Range':'bytes=0-99'}),env);assert.equal(r.status,206);assert.equal((await r.arrayBuffer()).byteLength,100);assert.equal((await worker.fetch(req(media.url),env)).status,401);const other=await worker.fetch(req('/api/state'),env);assert.equal((await worker.fetch(req(media.url,'GET',null,other.headers.get('Set-Cookie').split(';')[0]),env)).status,404);r=await worker.fetch(req('/api/upload','POST','not a valid image at all',cookie,{'Content-Type':'image/png'}),env);assert.equal(r.status,400);assert.equal((await worker.fetch(req(media.url,'DELETE',null,cookie),env)).status,200);assert.equal((await worker.fetch(req(media.url,'GET',null,cookie),env)).status,404);});
